// <auto-generated />
using DynamicHeaders_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicHeaders_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240427082733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicHeaders_api.Entities.SubHeadConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubHeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("subHeadConfigs");
                });

            modelBuilder.Entity("DynamicHeaders_api.Entities.SubHeadConfig", b =>
                {
                    b.OwnsMany("DynamicHeaders_api.Entities.SubHeadMetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("SubHeadConfigId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SubHeadConfigId", "Id");

                            b1.ToTable("subHeadConfigs");

                            b1.ToJson("MetaData");

                            b1.WithOwner()
                                .HasForeignKey("SubHeadConfigId");
                        });

                    b.Navigation("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
